name: ExtendAdminGUI
version: 1.0
author: blaise64
main: me.blaise.ExtendAdminGUI.Main
depend: [Spout]
commands:
    loadscreen:
        description: Load a screen file
        permission:
        aliases: loadscreen
    reloadscreens:
        description: Load a screen file
        permission:
        aliases: reloadscreens    
    regionscreen:
        description: Load a screen file
        permission:
        aliases: reloadscreens
