name: ExtendAdminGUI
version: 1.0
author: blaise64
main: me.blaise.ExtendAdminGUI.ExtendAdminGUIMain
depend: [Spout][Vault]
commands:
    loadscreen:
        description: Load a screen file
        permission:
        aliases: loadscreen
    reloadscreens:
        description: reload the screens files
        permission:
        aliases: reloadscreens    
    regionscreen:
        description: Load a region screen file
        permission:
        aliases: reloadscreens
    testscreen:
        description: Load a test screen file
        permission:
        aliases: testscreen
        
